config/urls.py
from django.contrib import admin

from django.urls import path, include

from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('home/', include('core.homepage.urls')),
    path('erp/', include('core.erp.urls')),
    path('user/', include('core.user.urls')),

    path('', include('pwa.urls')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.dashboard.views import DashboardView

from core.erp.views.music.views import MusicListView,MusicCreateView,MusicUpdateView,MusicDeleteView

from core.erp.views.live.views import LiveListView,LiveCreateView,LiveUpdateView,LiveDeleteView

from core.erp.views.category.views import CategoryListView,CategoryCreateView,CategoryUpdateView,CategoryDeleteView
from core.erp.views.publicidad.views import AdvertisingListView,AdvertisingCreateView,AdvertisingUpdateView,AdvertisingDeleteView

from core.erp.views.galery import views
app_name = 'erp'

urlpatterns = [
    # category
    
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # test
    # client
    path('music/list/', MusicListView.as_view(), name='music_list'),
    path('music/add/', MusicCreateView.as_view(), name='music_create'),
    path('music/update/<int:pk>/', MusicUpdateView.as_view(), name='music_update'),
    path('music/delete/<int:pk>/', MusicDeleteView.as_view(), name='music_delete'),
   
     # live
    path('live/list/', LiveListView.as_view(), name='live_list'),
    path('live/add/', LiveCreateView.as_view(), name='live_create'),
    path('live/update/<int:pk>/', LiveUpdateView.as_view(), name='live_update'),
    path('live/delete/<int:pk>/', LiveDeleteView.as_view(), name='live_delete'),
    
     # PUBLICIDAD
    path('advertising/list/', AdvertisingListView.as_view(), name='advertising_list'),
    path('advertising/add/', AdvertisingCreateView.as_view(), name='advertising_create'),
    path('advertising/update/<int:pk>/', AdvertisingUpdateView.as_view(), name='advertising_update'),
    path('advertising/delete/<int:pk>/', AdvertisingDeleteView.as_view(), name='advertising_delete'),

    #GALERIA

    path('galery/list/', views.gallery , name='galery_list'),
    path('galery/add/', views.addPhoto, name='galery_create'),
    path('galery/delete/<int:post_id>', views.eliminar, name='galery_delete'),



    #GALERIA

    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

]

core/user/urls.py
from django.urls import path
from core.user.views import UserListView,UserCreateView,UserUpdateView,UserDeleteView,UserChangeGroup,UserProfileView,UserChangePasswordView

app_name = 'user'

urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

core/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import model_to_dict

from crum import get_current_request

from config.settings import MEDIA_URL, STATIC_URL


class User(AbstractUser):
    image = models.ImageField(upload_to='users/%Y/%m/%d', null=True, blank=True)
    linkCelular = models.CharField(max_length=200, null=False, blank=False,verbose_name='Whatsapp')
    token = models.UUIDField(primary_key=False, editable=False, null=True, blank=True)

    def get_image(self):
        if self.image:
            return '{}{}'.format(MEDIA_URL, self.image)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')

    def toJSON(self):
        item = model_to_dict(self, exclude=['password', 'user_permissions', 'last_login'])
        if self.last_login:
            item['last_login'] = self.last_login.strftime('%Y-%m-%d')
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['image'] = self.get_image()
        item['full_name'] = self.get_full_name()
        item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]
        return item

    def get_group_session(self):
        try:
            request = get_current_request()
            groups = self.groups.all()
            if groups.exists():
                if 'group' not in request.session:
                    request.session['group'] = groups[0]
        except:
            pass

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        {% block contenidoPrincipal %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small> {{ user.username }} </small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block contenido %} {% endblock contenido %}
                </div>
            </div>
        </div>
        {% endblock contenidoPrincipal %}
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Mensaje!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'erp:dashboard' %}" class="nav-link">INICIO</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'user:user_change_group' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_profile' %}" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_change_password' %}" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{% url 'erp:dashboard' %}" class="brand-link">
        <img src="{% static 'img/mejia.jpg' %}"
             alt="MEJIAPROMUSIC Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">MEJIA PRO RADIO</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <div class="nav-link" style="color: white">
                        <i class="nav-icon fa fa-wrench"></i>
                        <p>
                            Panel de Administrador
                        </p>    
                    </div>
                </li>
                <li><hr class="dropdown-divider"></li>
                <!--ZONA MUSICA SLIDER MENU|-->
                <li class="nav-item menu-is-opening menu-close">
                    <a href="#" class="nav-link">
                      <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                        ZONA MÚSICA
                        </font></font>                        <i class="fa fa-music" aria-hidden="true"></i>

                      </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: block;">
                            
                        <li class="nav-item">
                            {% if perms.user.view_user %}
                            <a href="{% url 'erp:music_list' %}" class="nav-link">
                                <i class="fa fa-volume-up" aria-hidden="true"></i>
                                <p>
                                    Músicas
                                </p>
                            </a>
                            {% endif %}
                        </li>
                    </ul>
                  </li>

                <li><hr class="dropdown-divider"></li>
                <!--ZONA STREAMING SLIDER MENU|-->

                <li class="nav-item menu-is-opening menu-close">
                    <a href="#" class="nav-link">
                      <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                        ZONA STREAMING
                        </font></font><i class="fa fa-bullseye" aria-hidden="true"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: block;">
                            
                    <li class="nav-item">
                        {% if perms.user.view_user %}
                        <a href="{% url 'erp:live_list' %}" class="nav-link">
                            <i class="fa fa-link" aria-hidden="true"></i>
                            <p>
                                Live
                            </p>
                        </a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if perms.user.view_user %}
                        <a href="{% url 'erp:live_list' %}" class="nav-link">
                            <i class="fa fa-link" aria-hidden="true"></i>
                            <p>
                                Radio
                            </p>
                        </a>
                        {% endif %}
                    </li>
                    </ul>
                  </li>
                
                <li><hr class="dropdown-divider"></li>

                <!--ZONA GALERY SLIDER MENU-->
                <li class="nav-item  menu-is-opening menu-open">
                    <a href="#" class="nav-link " >
                      <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                        ZONA GALERÍA
                        
                    </font></font> <i class="fa fa-share-alt" aria-hidden="true"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: block;" >        
                        <li class="nav-item">
                            {% if perms.user.view_user %}
                            <a href="{% url 'erp:galery_list' %}" class="nav-link">
                                <i class="fa fa-camera-retro" aria-hidden="true"></i>

                                <p>
                                    Galería
                                </p>
                            </a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if perms.user.view_user %}
                            <a href="{% url 'erp:category_list' %}" class="nav-link">
                                <i class="fa fa-crop" aria-hidden="true"></i>
                                <p>
                                    Categoría
                                </p>
                            </a>
                            {% endif %}
                        </li>
                    </ul>
                  </li>
                
                <li><hr class="dropdown-divider"></li>

                <!--ZONA PUBLICIDAD SLIDER MENU-->

                <li class="nav-item  menu-is-opening menu-open">
                    <a href="#" class="nav-link " >
                      <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                        ZONA PUBLICIDAD
                        
                    </font></font><i class="fa fa-suitcase" aria-hidden="true"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: block;" >        
                        <li class="nav-item">
                            {% if perms.user.view_user %}
                            <a href="{% url 'erp:advertising_list' %}" class="nav-link">
                                <i class="fa fa-briefcase" aria-hidden="true"></i>
                                <p>
                                    Publicidad
                                </p>
                            </a>
                            {% endif %}
                        </li>
        
                    </ul>
                  </li>

                <li><hr class="dropdown-divider"></li>
                
                <!--ZONA PUBLICIDAD SLIDER MENU-->
                <li class="nav-item  menu-is-opening menu-open">
                    <a href="#" class="nav-link " >
                      <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                        ZONA USUARIOS
                    </font></font><i class="nav-icon fa fa-university"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: block;" >        
                    
                  <li class="nav-item">
                    {% if perms.user.view_user %}
                    <a href="{% url 'user:user_list' %}" class="nav-link">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <p>
                            Usuarios
                        </p>
                    </a>
                    {% endif %}
                </li>
        
                    </ul>
                  </li>
            </ul>
        </nav>
    </div>
</aside>