config/urls.py
from django.contrib import admin

from django.urls import path, include

from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('home/', include('core.homepage.urls')),
    path('erp/', include('core.erp.urls')),
    path('user/', include('core.user.urls')),

    path('', include('pwa.urls')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/homepage/urls.py
from django.urls import path

from core.homepage.views import IndexView, AboutView, MusicaView, RadioView,RadioOnlineView
from core.homepage import views

app_name = 'home'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('radioOnline/', RadioOnlineView.as_view(), name='radio_online'),
    path('musica/', MusicaView.as_view(), name='musica'),
    path('radio/', RadioView.as_view(), name='radio'),
     path('radiOnline/', RadioOnlineView.as_view(), name='radioOnline'),
    path('galery/', views.gallery , name='galery_list'),
    path('photo/<str:pk>/', views.viewPhoto, name='photo'),


]

core/homepage/models.py
from django.db import models

# Create your models here.
    

core/erp/views/galery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from core.erp.forms import PhotoForm
from core.erp.mixins import ValidatePermissionRequiredMixin
from django.core.exceptions import ValidationError
from django.contrib import messages
from core.erp.models import Photo,Category
from django.contrib.auth.decorators import  login_required


@login_required(login_url='/')
def eliminar(request, post_id):
    try:
        post = Photo.objects.get(pk=post_id)
    except Photo.DoesNotExist:
        messages.error(request, "NO EXISTE")
        return redirect('erp:galery_list')
    
    post.delete()
    messages.error(request, f"Se a eliminado la imagen correctamente!!")
    return redirect('erp:galery_list')



@login_required(login_url='/')
def gallery(request):
    category = request.GET.get('category')
    if category == None:
        photos = Photo.objects.all()
    else:
        photos = Photo.objects.filter(category__name=category)

    categories = Category.objects.all()
    context = {'categories': categories, 'photos': photos ,'title':'Galeria'}
    return render(request, 'Galery/list.html', context)

@login_required(login_url='/')
def addPhoto(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images')

        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(
                name=data['category_new'])
        else:
            category = None

        for image in images:
            photo = Photo.objects.create(
                category=category,
                description=data['description'],
                image=image,
            )

        return redirect('erp:galery_list')

    context = {'categories': categories}
    return render(request, 'Galery/create.html', context)




#VALIDACIONES


def verificar(nro):
    l = len(nro)
    if l == 10 or l == 13: # verificar la longitud correcta
        cp = int(nro[0:2])
        if cp >= 1 and cp <= 22: # verificar codigo de provincia
            tercer_dig = int(nro[2])
            if tercer_dig >= 0 and tercer_dig < 6 : # numeros enter 0 y 6
                if l == 10:
                    return __validar_ced_ruc(nro,0)                       
                elif l == 13:
                    return __validar_ced_ruc(nro,0) and nro[10:13] != '000' # se verifica q los ultimos numeros no sean 000
            elif tercer_dig == 6:
                return __validar_ced_ruc(nro,1) # sociedades publicas
            elif tercer_dig == 9: # si es ruc
                return __validar_ced_ruc(nro,2) # sociedades privadas
            else:
                raise Exception(u'Tercer digito invalido') 
        else:
            raise Exception(u'Codigo de provincia incorrecto') 
    else:
        raise Exception(u'Longitud incorrecta del numero ingresado')
    
def __validar_ced_ruc(nro,tipo):
    total = 0
    if tipo == 0: # cedula y r.u.c persona natural
        base = 10
        d_ver = int(nro[9])# digito verificador
        multip = (2, 1, 2, 1, 2, 1, 2, 1, 2)
    elif tipo == 1: # r.u.c. publicos
        base = 11
        d_ver = int(nro[8])
        multip = (3, 2, 7, 6, 5, 4, 3, 2 )
    elif tipo == 2: # r.u.c. juridicos y extranjeros sin cedula
        base = 11
        d_ver = int(nro[9])
        multip = (4, 3, 2, 7, 6, 5, 4, 3, 2)
    for i in range(0,len(multip)):
        p = int(nro[i]) * multip[i]
        if tipo == 0:
            total+=p if p < 10 else int(str(p)[0])+int(str(p)[1])
        else:
            total+=p
    mod = total % base
    val = base - mod if mod != 0 else 0
    return val == d_ver

def vcedula(texto):
    # sin ceros a la izquierda
    nocero = texto.strip("0")
    
    cedula = int(nocero,0)
    verificador = cedula%10
    numero = cedula//10
    
    # mientras tenga números
    suma = 0
    while (numero > 0):
        
        # posición impar
        posimpar = numero%10
        numero   = numero//10
        posimpar = 2*posimpar
        if (posimpar  > 9):
            posimpar = posimpar-9
        
        # posición par
        pospar = numero%10
        numero = numero//10
        
        suma = suma + posimpar + pospar
    
    decenasup = suma//10 + 1
    calculado = decenasup*10 - suma
    if (calculado  >= 10):
        calculado = calculado - 10

    if (calculado == verificador):
        validado = 1
    else:
        validado = 0
        
    return (validado)

core/homepage/views.py
from django.views.generic import TemplateView


from django.shortcuts import render, redirect 

import json
import os
from django.http import HttpResponse

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect

from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, View
from django.conf import settings
from xhtml2pdf import pisa
from django.template.loader import get_template

from core.erp.forms import MusicForm, LiveForm
from core.erp.mixins import ValidatePermissionRequiredMixin
from core.erp.models import Music, Live
from core.erp.models import Photo,Category
from core.erp.models import Advertising


# Create your views here.
class IndexView(ListView):
    model = Advertising
    template_name = 'home/body.html'
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []               
                for i in Advertising.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado Publicidad'
        context['create_url'] = reverse_lazy('erp:advertising_create')
        context['list_url'] = reverse_lazy('erp:advertising_list')
        context['entity'] = 'Publicidad'
        context['var'] = self.get_queryset()
        return context




class AboutView(TemplateView):
    template_name = 'home/about.html'




class RadioOnlineView(TemplateView):
    template_name = 'home/radioOnline.html'

class MusicaView(ListView):
    model = Music
    template_name = "home/musica.html"
    #permission_required = 'view_music'
    @method_decorator(csrf_exempt)
    #@method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                position = 1
                for i in Music.objects.all():
                    item = i.toJSON()
                    item['position'] = position
                    data.append(item)
                    position += 1
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)        
        return JsonResponse(data,safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tittle'] = 'Listado de Curso'
        context['create_url'] = reverse_lazy('erp:curso_create')
        context['list_url'] = reverse_lazy('erp:curso_list')
        context['entity'] = 'Curso'
        context['curso'] = self.get_queryset()   #agregamos la consulta al contexto
        #context['silabo'] = self.get_queryset()#context['form'] = self.form_class
        return context
    

class RadioView(ListView):
    model = Live
    template_name = "home/radio.html"
    #permission_required = 'view_music'
    @method_decorator(csrf_exempt)
    #@method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                position = 1
                for i in Music.objects.all():
                    item = i.toJSON()
                    item['position'] = position
                    data.append(item)
                    position += 1
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)        
        return JsonResponse(data,safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tittle'] = 'Listado de Curso'
        context['create_url'] = reverse_lazy('erp:curso_create')
        context['list_url'] = reverse_lazy('erp:curso_list')
        context['entity'] = 'Curso'
        context['curso'] = self.get_queryset()   #agregamos la consulta al contexto
        #context['silabo'] = self.get_queryset()#context['form'] = self.form_class
        return context

def viewPhoto(request, pk):
    photo = Photo.objects.get(id=pk)
    return render(request, 'home/imagenview.html', {'photo': photo})


def gallery(request):
    category = request.GET.get('category')
   
    
    if category == None:
        photos = Photo.objects.all()
    else:
        photos = Photo.objects.filter(category__name=category)

    categories = Category.objects.all()
    context = {'categories': categories, 'photos': photos}
    return render(request, 'home/galery.html', context)


class AdvertisingListView(LoginRequiredMixin, ListView):
    model = Advertising
    template_name = 'home/body.html'
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []               
                for i in Advertising.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado Publicidad'
        context['create_url'] = reverse_lazy('erp:advertising_create')
        context['list_url'] = reverse_lazy('erp:advertising_list')
        context['entity'] = 'Publicidad'
        context['var'] = self.get_queryset()
        return context

core/homepage/templates/home/body.html
{% extends 'index.html' %}{% load static %} {% block body %}
<body >
  {% include 'home/header.html' %}


  <!-- Hero Start -->
  <section class="hero">
    <div class="container">
      <div class="row">
        <div class="col-12 offset-md-1 col-md-11">
          <div class="swiper-container hero-slider">
            <div class="swiper-wrapper">
              <div class="swiper-slide slide-content d-flex align-items-center">
                <div class="single-slide" style="color: white">
                  <h1
                    data-aos="fade-right"
                    data-aos-delay="200"
                    style="color: white"
                  >
                  ASOCIACIÓN   
                  <br />
                    MEJIA PRO MUSIC
                  </h1>
                  <p
                    data-aos="fade-right"
                    data-aos-delay="600"
                    style="color: white"
                  >
                  Deejays, Animadores y Productores..
                  </p>
                  <a
                    data-aos="fade-right"
                    data-aos-delay="900"
                    href="{% url 'home:galery_list' %}"
                    class="btn btn-primary"
                    >GALERÍA</a
                  >
                </div>
              </div>
              <div class="swiper-slide slide-content d-flex align-items-center">
                <div class="single-slide">
                  <h1
                    data-aos="fade-right"
                    data-aos-delay="200"
                    style="color: white; font-size:60px"
                  >
                    MEJIA PRO RADIO<br />
                    "LA MEJOR PROGRAMACIÓN"
                  </h1>
                  <p
                    data-aos="fade-right"
                    data-aos-delay="600"
                    style="color: white"
                  >
                  Disfrute de todos nuestros programas con contenidos de información <br> periodística, educativa, cultural y de entretenimiento..
                  </p>
                  <a
                    data-aos="fade-right"
                    data-aos-delay="900"
                    href="{% url 'home:radioOnline' %}"
                    class="btn btn-primary"
                    >MEJÍA PRO RADIO</a
                  >
                </div>
              </div>
             
              <div class="swiper-slide slide-content d-flex align-items-center">
                <div class="single-slide">
                  <h1
                    data-aos="fade-right"
                    data-aos-delay="200"
                    style="color: white; font-size:60px"
                  >
                  ACTUALIZACIONES
                  <br />
                  PACKS MENSUALES
                  </h1>
                  <p
                    data-aos="fade-right"
                    data-aos-delay="600"
                    style="color: white"
                  >
                    Con nuestras versiones para Deejay como: <br> Remix, Extended, Intros, Starter, Opening, Mashup y mucho más. 
                  </p>
                  <a
                    data-aos="fade-right"
                    data-aos-delay="900"
                    href="{% url 'home:musica' %}"
                    class="btn btn-primary"
                    >MÚSICA</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Add Control -->
      <span class="arr-left"><i class="fa fa-angle-left"></i></span>
      <span class="arr-right"><i class="fa fa-angle-right"></i></span>
    </div>
    <div class="texture"></div>
    <div class="diag-bg"></div>
  </section>
  <!-- Hero End -->
  <!-- Call To Action Start -->
  <br>
  <section class="cta" data-aos="fade-up" data-aos-delay="0" >
    <div class="container">
      <div
        class="cta-content d-xl-flex align-items-center justify-content-around text-center text-xl-left"
      >
        <div class="content" data-aos="fade-right" data-aos-delay="200">
          <h2>Transmisiones en vivo TV Radio</h2>
          <p>Tu gran alternativa en radio Online, con los mejores DJ's.</p>
        </div>
        <div
          class="subscribe-btn"
          data-aos="fade-left"
          data-aos-delay="400"
          data-aos-offset="0"
        >
          <a href="{% url 'home:radio' %}" class="btn btn-primary"
            >MÍRANOS EN VIVO - MEJIA PRO RADIO</a
          >
        </div>
      </div>
    </div>
  </section>
  <!-- Call To Action End -->
  <!-- PUBLICIDAD Start -->
  <!-- Hero Start -->
  <br>
  <section class="hero3" >
    <div class="container">
      <div class="title text-center">
        <h6 class="title-primary">ZONA PUBLICITARIA</h6>
        <h1 class="title-blue">NUESTROS AUSPICIANTES</h1>
      
      </div>
      <div class="row" >

        <div class="swiper-container hero-slider">
          
          <div class="swiper-wrapper">
            {% for c in var %}

            <div class="swiper-slide slide-content d-flex">
  
              <div class="single-slide">
              
                  <img
                  src="{{ c.image.url }}"
                  alt=""
                  style="margin-left:20%"
                  height="400px"
                  width="800px"
                />     
                <center>
                  <div
                  class="subscribe-btn"
                  data-aos="fade-left"
                  data-aos-delay="400"
                  data-aos-offset="0"
                >
                  <a href="{{ c.link }}" class="btn btn-primary" target="_blank"
                    >VISITANOS - {{ c.nombre }} </a>
                  >
                </div>
                </center>
              </div>
              
            </div>
            {% endfor %}

          </div>

        </div>

      </div>
    </div>
    
    <div class="texture"></div>
    <div class="diag-bg"></div>
    <br> <br>
<div class="container">
  <div class="row">

  <div class="col-md-4">
    <a href="https://www.facebook.com/mejiapromusic" target="_blank">
      <img src="{% static 'assets/mejia/pauta.jpg' %}" alt="..." class="rounded-circle" width="100%" height="100%">
    </a>

  </div>  <div class="col-md-4">
    <a href="https://www.facebook.com/mejiapromusic" target="_blank">
      <img src="{% static 'assets/mejia/TU2.jpg' %}" alt="..." class="rounded-circle" width="100%" height="100%">
    </a>
    
  </div>  <div class="col-md-4">
    <a href="https://www.facebook.com/mejiapromusic" target="_blank">
      <img src="{% static 'assets/mejia/pauta.jpg' %}" alt="..." class="rounded-circle" width="100%" height="100%">
    </a>
  </div>
  </div>

</div>

  </section>
 <!-- Inicio. radio hosting USAstreams.com html5 player -->
<!-- Licencia: GRATIS-XDF4543ERF -->
<iframe name="contenedorPlayer" class="cuadroBordeado" allow="autoplay" width="100%" height="120px" marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0 scrolling=no  src="https://cp.usastreams.com/pr2g/APPlayerRadioHTML5.aspx?stream=https://ssradioonline.com/proxy/mejiapro?mp=/stream&fondo=05&formato=mpeg&color=3&titulo=2&autoStart=1&vol=5&tipo=201&nombre=MEJ%c3%8dA+PRO+RADIO&imagen=https://cp.usastreams.com/playerHTML5/img/cover.png&server=https://ssradioonline.com/status.xslCHUMILLASmount=/proxy/status.xslCHUMILLASmount=/mejiaproCHUMILLASmp=/status.xslCHUMILLASmount=/stream"></iframe>

<!-- Fin. USAstreams.com html5 player -->
  <!-- Hero End -->
  <!-- Featured End -->
  <!-- Pricing Start -->
  
  <!-- Pricing End -->
  <!-- Testimonial and Clients Start -->

  <!-- Call To Action 2 End -->
  <!-- Footer Start -->
  {% include 'home/footer.html' %}

  <!-- Footer Endt -->
  <!--jQuery-->
  <script src="{% static 'assets/js/jquery-3.3.1.js' %}"></script>
  <!--Plugins-->
  <script src="{% static 'assets/js/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'assets/js/loaders.css.js' %}"></script>
  <script src="{% static 'assets/js/aos.js' %}"></script>
  <script src="{% static 'assets/js/swiper.min.js' %}"></script>
  <script src="{% static 'assets/js/lightgallery-all.min.js' %}"></script>
  <!--Template Script-->
  <script src="{% static 'assets/js/main.js' %}"></script>
  

</body>
{% endblock %}

core/homepage/templates/home/footer.html
{% load static %}

<footer>
    <!-- Widgets Start -->

    <!-- Widgets End -->
    <!-- Foot Note Start -->
    <div class="foot-note">
      <div class="container">
        <div
          class="footer-content text-center text-lg-left d-lg-flex justify-content-between align-items-center"
        >
          
        <p class="mb-0" data-aos="fade-right" data-aos-offset="0">
            &copy; <strong>2021 All Rights Reserved.</strong>  
            <a
              href="https://www.facebook.com/mejiapromusic"
              target="_blank"
              class="fh5-link"
              > <strong>Mejía Pro Music</strong></a
            >.
          </p>
         
        </div>
      </div>
    </div>
    <!-- Foot Note End -->
  </footer>

  
    <!-- Footer Endt -->
    <!--jQuery-->
    <script src="{% static 'assets/js/jquery-3.3.1.js' %}"></script>
    <!--Plugins-->
    <script src="{% static 'assets/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'assets/js/loaders.css.js' %}"></script>
    <script src="{% static 'assets/js/aos.js' %}"></script>
    <script src="{% static 'assets/js/swiper.min.js' %}"></script>
    <script src="{% static 'assets/js/lightgallery-all.min.js' %}"></script>
    <!--Template Script-->
    <script src="{% static 'assets/js/main.js' %}"></script>
  

core/homepage/templates/home/galery.html
{% extends 'index.html' %}
{% load static %}
{% block tituloPrincipal %}
<title>Galería Mejia Pro Music</title>    
{% endblock %}
{% block body %}

<body style="height:100%">
    {% include 'home/header.html' %}

        <!-- Hero Start -->
        
        <section class="hero8 pricing-table" style="height:100%">
              <div style="margin-top:10%; color:black ;" >
       
                <div class="container">
                    
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title" style="text-align:center">
                GALERÍA
            </h3>
        </div>
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
        
                        <div class="card">
                            <div class="card-header" style="background:#210B61; color:white">
                                CATEGORÍAS
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <a href="{% url 'home:galery_list' %}">TODO</a>
                                </li>
                                {% for category in categories %}
                                <li class=" list-group-item">
                                    <a href="{% url 'home:galery_list' %}?category={{category.name}}">
                                        {{category.name}}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
        
                    </div>
                    <div class="col-md-9">
                        <div class="row">
        
                            {% for photo in photos %}
                            <div class="col-md-4">
                                <div class="card my-2">
                                    
                                    <img class="image-thumbail" style="margin-left: 12px; margin-top:5px;" src="{{photo.image.url}}" alt="Card image cap" width="210px" height="200px">
        
                                    <div class="card-body">
                                        <small>Categoría: {{photo.category.name}}</small>
                                    </div>
                                    <a href="{% url 'home:photo' photo.id %}" class="btn btn-outline-dark btn-sm m-1" style="background:#210B61; color:white">Ver</a>

                                </div>
                            </div>
                            {% empty %}
                           <center>
                            <h3>NO HAY IMAGENES...</h3>
                           </center>
                            {% endfor %}
     
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
                </div>
                 
                </div>
          
            </div>
            <iframe style="margin-top: 10%;" name="contenedorPlayer" class="cuadroBordeado" allow="autoplay" width="0px" height="0px" marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0 scrolling=no  src="https://cp.usastreams.com/pr2g/APPlayerRadioHTML5.aspx?stream=https://ssradioonline.com/proxy/mejiapro?mp=/stream&fondo=05&formato=mpeg&color=14&titulo=2&autoStart=1&vol=5&tipo=4&nombre=Radio+TOP40&imagen=https://cp.usastreams.com/playerHTML5/img/cover.png"></iframe>
            
            </section>
              
 
        <h1 style="margin-top: 5%;" hidden></h1>

        </button>
        

    {% include 'home/footer.html' %}

</body>
{% endblock body %}

core/homepage/templates/home/header.html
{% load static %}

<!-- Loader Start -->
  <div class="css-loader">
    <div
      class="loader-inner line-scale d-flex align-items-center justify-content-center"
    ></div>
  </div>
  <!-- Loader End -->
  <!-- Header Start -->
  <header class="position-absolute w-100">
    <div class="container">
      <div
        class="top-header d-none d-sm-flex justify-content-between align-items-center"
      >
        <div class="contact">
         
          <a href="mailto:mejiapromusic2018@gmail.com?Subject=Mejía%20Pro%20Music"
            ><i class="fa fa-envelope" aria-hidden="true"></i
            >mejiapromusic2018@gmail.com</a
          >
        </div>
        <nav class="d-flex aic">
          <a href="{% url 'login' %}" class="login"
            ></a
          >
          <ul class="nav social d-none d-md-flex">
            <li>
              <a href="https://www.facebook.com/mejiapromusic" target="_blank"
                ><i class="fa fa-facebook"></i
              ></a>
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UC6hGEhjPJjv5h1qTXkG8cYA" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i></i></a>
            </li>
            <li>
              <a href="https://www.instagram.com/mejiapromusic/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            </li>
          </ul>
        </nav>
      </div>
      <nav class="navbar navbar-expand-md navbar-light">
        <a class="navbar-brand" href="{% url 'index' %}"
          ><img
            src="{% static 'assets/mejia/mejia4.png' %}"
            alt="Multipurpose"
            style="height:100px ; width: 200px;"
        /></a>  
        <div class="group d-flex align-items-center">
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="login-icon d-sm-none" href="#"
            ><i class="fa fa-user"></i
          ></a>
        </div>
        <a class="search-icon d-none d-md-block" href="#"
          ></a>
        <div
          class="collapse navbar-collapse justify-content-end"
          id="navbarSupportedContent"
        >
          <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'index' %}" style="font-size:20px"> <strong>Inicio</strong> </a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'home:radioOnline' %}"style="font-size:20px"> <strong>Radio</strong> </a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'home:radio' %}"style="font-size:20px"> <strong>TV Radio</strong> </a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:musica' %}"style="font-size:20px"><strong>Música</strong></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:galery_list' %}"style="font-size:20px"><strong>Galería</strong></a>
            </li>            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:about' %}"style="font-size:20px"><strong>Nosotros</strong></a>
            </li>

          </ul>
          <form class="bg-white search-form" method="get" id="searchform">
            <div class="input-group">
              <input
                class="field form-control"
                id="s"
                name="s"
                type="text"
                placeholder="Search"
              />
              <span class="input-group-btn">
                <input
                  class="submit btn btn-primary"
                  id="searchsubmit"
                  name="submit"
                  type="submit"
                  value="Search"
                />
              </span>
            </div>
          </form>
        </div>
      </nav>
    </div>
  </header>
  <!-- Header End -->