config/urls.py
from django.contrib import admin

from django.urls import path, include

from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('home/', include('core.homepage.urls')),
    path('erp/', include('core.erp.urls')),
    path('user/', include('core.user.urls')),

    path('', include('pwa.urls')),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.dashboard.views import DashboardView

from core.erp.views.music.views import MusicListView,MusicCreateView,MusicUpdateView,MusicDeleteView

from core.erp.views.live.views import LiveListView,LiveCreateView,LiveUpdateView,LiveDeleteView

from core.erp.views.category.views import CategoryListView,CategoryCreateView,CategoryUpdateView,CategoryDeleteView
from core.erp.views.publicidad.views import AdvertisingListView,AdvertisingCreateView,AdvertisingUpdateView,AdvertisingDeleteView

from core.erp.views.galery import views
app_name = 'erp'

urlpatterns = [
    # category
    
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # test
    # client
    path('music/list/', MusicListView.as_view(), name='music_list'),
    path('music/add/', MusicCreateView.as_view(), name='music_create'),
    path('music/update/<int:pk>/', MusicUpdateView.as_view(), name='music_update'),
    path('music/delete/<int:pk>/', MusicDeleteView.as_view(), name='music_delete'),
   
     # live
    path('live/list/', LiveListView.as_view(), name='live_list'),
    path('live/add/', LiveCreateView.as_view(), name='live_create'),
    path('live/update/<int:pk>/', LiveUpdateView.as_view(), name='live_update'),
    path('live/delete/<int:pk>/', LiveDeleteView.as_view(), name='live_delete'),
    
     # PUBLICIDAD
    path('advertising/list/', AdvertisingListView.as_view(), name='advertising_list'),
    path('advertising/add/', AdvertisingCreateView.as_view(), name='advertising_create'),
    path('advertising/update/<int:pk>/', AdvertisingUpdateView.as_view(), name='advertising_update'),
    path('advertising/delete/<int:pk>/', AdvertisingDeleteView.as_view(), name='advertising_delete'),

    #GALERIA

    path('galery/list/', views.gallery , name='galery_list'),
    path('galery/add/', views.addPhoto, name='galery_create'),
    path('galery/delete/<int:post_id>', views.eliminar, name='galery_delete'),



    #GALERIA

    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

]

core/erp/views/category/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from core.erp.forms import CategoryForm
from core.erp.mixins import ValidatePermissionRequiredMixin
from core.erp.models import Category


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'Category/list.html'
    permission_required = 'view_live'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []               
                for i in Category.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Categorias'
        context['create_url'] = reverse_lazy('erp:category_create')
        context['list_url'] = reverse_lazy('erp:category_list')
        context['entity'] = 'Categoria'
        return context


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'Category/create.html'
    success_url = reverse_lazy('erp:category_list')
    permission_required = 'add_category'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación una Categoria'
        context['entity'] = 'Categoria'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'Category/create.html'
    success_url = reverse_lazy('erp:category_list')
    permission_required = 'change_category'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de una Categoria'
        context['entity'] = 'Categoria'
        context['list_url'] = self.success_url
        context['action'] = 'edit'
        return context


class CategoryDeleteView(LoginRequiredMixin,  DeleteView):
    model = Category
    template_name = 'Category/delete.html'
    success_url = reverse_lazy('erp:category_list')
    permission_required = 'delete_category'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de un Live'
        context['entity'] = 'Live'
        context['list_url'] = self.success_url
        return context


#VALIDACIONES


def verificar(nro):
    l = len(nro)
    if l == 10 or l == 13: # verificar la longitud correcta
        cp = int(nro[0:2])
        if cp >= 1 and cp <= 22: # verificar codigo de provincia
            tercer_dig = int(nro[2])
            if tercer_dig >= 0 and tercer_dig < 6 : # numeros enter 0 y 6
                if l == 10:
                    return __validar_ced_ruc(nro,0)                       
                elif l == 13:
                    return __validar_ced_ruc(nro,0) and nro[10:13] != '000' # se verifica q los ultimos numeros no sean 000
            elif tercer_dig == 6:
                return __validar_ced_ruc(nro,1) # sociedades publicas
            elif tercer_dig == 9: # si es ruc
                return __validar_ced_ruc(nro,2) # sociedades privadas
            else:
                raise Exception(u'Tercer digito invalido') 
        else:
            raise Exception(u'Codigo de provincia incorrecto') 
    else:
        raise Exception(u'Longitud incorrecta del numero ingresado')
    
def __validar_ced_ruc(nro,tipo):
    total = 0
    if tipo == 0: # cedula y r.u.c persona natural
        base = 10
        d_ver = int(nro[9])# digito verificador
        multip = (2, 1, 2, 1, 2, 1, 2, 1, 2)
    elif tipo == 1: # r.u.c. publicos
        base = 11
        d_ver = int(nro[8])
        multip = (3, 2, 7, 6, 5, 4, 3, 2 )
    elif tipo == 2: # r.u.c. juridicos y extranjeros sin cedula
        base = 11
        d_ver = int(nro[9])
        multip = (4, 3, 2, 7, 6, 5, 4, 3, 2)
    for i in range(0,len(multip)):
        p = int(nro[i]) * multip[i]
        if tipo == 0:
            total+=p if p < 10 else int(str(p)[0])+int(str(p)[1])
        else:
            total+=p
    mod = total % base
    val = base - mod if mod != 0 else 0
    return val == d_ver

def vcedula(texto):
    # sin ceros a la izquierda
    nocero = texto.strip("0")
    
    cedula = int(nocero,0)
    verificador = cedula%10
    numero = cedula//10
    
    # mientras tenga números
    suma = 0
    while (numero > 0):
        
        # posición impar
        posimpar = numero%10
        numero   = numero//10
        posimpar = 2*posimpar
        if (posimpar  > 9):
            posimpar = posimpar-9
        
        # posición par
        pospar = numero%10
        numero = numero//10
        
        suma = suma + posimpar + pospar
    
    decenasup = suma//10 + 1
    calculado = decenasup*10 - suma
    if (calculado  >= 10):
        calculado = calculado - 10

    if (calculado == verificador):
        validado = 1
    else:
        validado = 0
        
    return (validado)

core/erp/views/dashboard/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView


from random import randint


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        request.user.get_group_session()
        return super().get(request, *args, **kwargs)

    

core/erp/views/galery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from core.erp.forms import PhotoForm
from core.erp.mixins import ValidatePermissionRequiredMixin
from django.core.exceptions import ValidationError
from django.contrib import messages
from core.erp.models import Photo,Category
from django.contrib.auth.decorators import  login_required


@login_required(login_url='/')
def eliminar(request, post_id):
    try:
        post = Photo.objects.get(pk=post_id)
    except Photo.DoesNotExist:
        messages.error(request, "NO EXISTE")
        return redirect('erp:galery_list')
    
    post.delete()
    messages.error(request, f"Se a eliminado la imagen correctamente!!")
    return redirect('erp:galery_list')



@login_required(login_url='/')
def gallery(request):
    category = request.GET.get('category')
    if category == None:
        photos = Photo.objects.all()
    else:
        photos = Photo.objects.filter(category__name=category)

    categories = Category.objects.all()
    context = {'categories': categories, 'photos': photos ,'title':'Galeria'}
    return render(request, 'Galery/list.html', context)

@login_required(login_url='/')
def addPhoto(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images')

        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(
                name=data['category_new'])
        else:
            category = None

        for image in images:
            photo = Photo.objects.create(
                category=category,
                description=data['description'],
                image=image,
            )

        return redirect('erp:galery_list')

    context = {'categories': categories}
    return render(request, 'Galery/create.html', context)




#VALIDACIONES


def verificar(nro):
    l = len(nro)
    if l == 10 or l == 13: # verificar la longitud correcta
        cp = int(nro[0:2])
        if cp >= 1 and cp <= 22: # verificar codigo de provincia
            tercer_dig = int(nro[2])
            if tercer_dig >= 0 and tercer_dig < 6 : # numeros enter 0 y 6
                if l == 10:
                    return __validar_ced_ruc(nro,0)                       
                elif l == 13:
                    return __validar_ced_ruc(nro,0) and nro[10:13] != '000' # se verifica q los ultimos numeros no sean 000
            elif tercer_dig == 6:
                return __validar_ced_ruc(nro,1) # sociedades publicas
            elif tercer_dig == 9: # si es ruc
                return __validar_ced_ruc(nro,2) # sociedades privadas
            else:
                raise Exception(u'Tercer digito invalido') 
        else:
            raise Exception(u'Codigo de provincia incorrecto') 
    else:
        raise Exception(u'Longitud incorrecta del numero ingresado')
    
def __validar_ced_ruc(nro,tipo):
    total = 0
    if tipo == 0: # cedula y r.u.c persona natural
        base = 10
        d_ver = int(nro[9])# digito verificador
        multip = (2, 1, 2, 1, 2, 1, 2, 1, 2)
    elif tipo == 1: # r.u.c. publicos
        base = 11
        d_ver = int(nro[8])
        multip = (3, 2, 7, 6, 5, 4, 3, 2 )
    elif tipo == 2: # r.u.c. juridicos y extranjeros sin cedula
        base = 11
        d_ver = int(nro[9])
        multip = (4, 3, 2, 7, 6, 5, 4, 3, 2)
    for i in range(0,len(multip)):
        p = int(nro[i]) * multip[i]
        if tipo == 0:
            total+=p if p < 10 else int(str(p)[0])+int(str(p)[1])
        else:
            total+=p
    mod = total % base
    val = base - mod if mod != 0 else 0
    return val == d_ver

def vcedula(texto):
    # sin ceros a la izquierda
    nocero = texto.strip("0")
    
    cedula = int(nocero,0)
    verificador = cedula%10
    numero = cedula//10
    
    # mientras tenga números
    suma = 0
    while (numero > 0):
        
        # posición impar
        posimpar = numero%10
        numero   = numero//10
        posimpar = 2*posimpar
        if (posimpar  > 9):
            posimpar = posimpar-9
        
        # posición par
        pospar = numero%10
        numero = numero//10
        
        suma = suma + posimpar + pospar
    
    decenasup = suma//10 + 1
    calculado = decenasup*10 - suma
    if (calculado  >= 10):
        calculado = calculado - 10

    if (calculado == verificador):
        validado = 1
    else:
        validado = 0
        
    return (validado)

core/erp/templates/Galery/create.html
{% extends 'layout.html' %}
{% load static %}

{% load widget_tweaks %}
{% block head %}
<script src="{% static 'lib/moment-2.25.3/moment-with-locales.js' %}"></script>
<script src="{% static 'lib/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.js' %}"></script>
<link href="{% static 'lib/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet"/>

<link href="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.css' %}" rel="stylesheet"/>
<script src="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.js' %}"></script>
{% endblock %}
{% block contenido %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Subir Imagenes
                </h3>

            </div>
           <div class="card-content">
            {% csrf_token %}

            <div class="form-group m-3">
                <label>Descripción</label>
                <input required name="description" type="text" placeholder="Ingresa la  descripción"
                    class="form-control">
            </div>

            <div class="form-group m-3">
                <label>Selecciona el álbum</label>
                <select name="category" class="form-control">
                    <option value='none'>Selecciona el álbum...</option>

                    {% for category in categories %}
                    <option value='{{category.id}}'>{{category.name}}</option>
                    {% endfor %}
                </select>
            </div>


            <div class="form-group m-3">
                <label>Crea un nuevo Álbum</label>
                <input name="category_new" type="text" placeholder="Crea un nuevo Almbum"
                    class="form-control">
                <p style="color: red">Este campo debe ser llenado solo si necesitas crear un nuevo álbum...</p>
            </div>

            <div class="form-group m-3">
                <label>Subir Imagen</label>
                <input required name="images" type="file" multiple class="form-control-file">
            </div>


           </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{% url 'erp:galery_list' %}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>    
{% endblock %}

core/erp/templates/Galery/delete.html
{% extends 'delete.html' %}

core/erp/templates/Galery/list.html
{% extends 'layout.html' %}
{% load static %}
<!--CARGAMOS LAS LIBRERIAS DEL DATATABLES-->    
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    
    {% block head_list %}
        
    {% endblock head_list %}
        

{% endblock head %}
<!--CONTENIDO PRINCIPAL-->
{% block contenido %}
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                
                {{title}}
                    
            </h3>
        </div>
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
        
                        <div class="card">
                            <div class="card-header">
                                Categorías
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <a href="{% url 'erp:galery_list' %}">Todo</a>
                                </li>
                                {% for category in categories %}
                                <li class=" list-group-item">
                                    <a href="{% url 'erp:galery_list' %}?category={{category.name}}">
                                        {{category.name}}
                                    </a>
                                </li>
                                {% endfor %}
        
        
                                <a href="{% url 'erp:galery_create' %}" class="btn btn-dark btn-block btn-sm m-1">Agregar Foto</a>
        
                            </ul>
                        </div>
        
                    </div>
                    <div class="col-md-9">
                        <div class="row">
        
                            {% for photo in photos %}
                            <div class="col-md-4">
                                <div class="card my-2">
                                    
                                    <img class="image-thumbail" style="margin-left: 12px;" src="{{photo.image.url}}" alt="Card image cap" width="250px" height="200px">
        
                                    <div class="card-body">
                                        <small>Category: {{photo.category.name}}</small>
                                    </div>
                                    <a href="#" class="btn btn-outline-dark btn-sm m-1">Ver</a>
                                    <a href="{% url 'erp:galery_delete' photo.id %}" type="button" class="btn btn-danger">Borrar</a>

                                </div>
                            </div>
                            {% empty %}
                           <center>
                            <h3>NO HAY IMAGENES...</h3>
                           </center>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
       
{% endblock contenido %}